name: Generate Stats SVGs

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  update-stats:
    name: Update GitHub Stats
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      
      - name: Fetch SVGs
        run: |
          mkdir -p dist
          # Retry mechanism just in case the API is temporarily flaky
          curl -s --retry 3 --retry-delay 5 -o dist/github-stats.svg "https://github-readme-stats.vercel.app/api?username=${{ github.repository_owner }}&show_icons=true&theme=radical&hide_border=true&count_private=true"
          curl -s --retry 3 --retry-delay 5 -o dist/github-top-langs.svg "https://github-readme-stats.vercel.app/api/top-langs/?username=${{ github.repository_owner }}&layout=compact&theme=radical&hide_border=true&langs_count=8"
          curl -s --retry 3 --retry-delay 5 -o dist/github-trophies.svg "https://github-profile-trophy.vercel.app/?username=${{ github.repository_owner }}&theme=radical&no-frame=true&row=1&column=6"
          
      - name: Push to output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
          keep_history: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
